import { Borough } from 'constants/boroughs'
import { HumanizedDescription } from 'constants/violationDescriptions'
import { Violation } from 'types/violations'

import mergeDuplicateViolations from '.'

describe('mergeDuplicateViolations', () => {
  it('should merge violations with the same summons number', () => {
    const violations: Violation[] = [
      {
        amountDue: 0,
        dateFirstObserved: undefined,
        daysParkingInEffect: undefined,
        feetFromCurb: undefined,
        fineAmount: 50,
        fined: 50,
        formattedTime: '2023-07-02T19:55:00.000-04:00',
        formattedTimeEastern: '2023-07-02T19:55:00.000-04:00',
        formattedTimeUtc: '2023-07-02T23:55:00.000Z',
        fromDatabases: [
          {
            dataUpdatedAt: '2025-03-29T09:21:18.000Z',
            endpoint: 'https://data.cityofnewyork.us/resource/nc67-uf89.json',
            name: 'Open Parking and Camera Violations',
          },
        ],
        fromHoursInEffect: undefined,
        houseNumber: undefined,
        humanizedDescription:
          'School Zone Speed Camera Violation' as HumanizedDescription,
        interestAmount: 0,
        intersectingStreet: undefined,
        issueDate: '07/02/2023',
        issuerCode: undefined,
        issuerCommand: undefined,
        issuerPrecinct: undefined,
        issuerSquad: undefined,
        issuingAgency: 'V',
        judgmentEntryDate: undefined,
        lawSection: undefined,
        location: undefined,
        meterNumber: undefined,
        outstanding: 0,
        paid: 50,
        paymentAmount: 50,
        penaltyAmount: 0,
        plateId: '1E65H',
        plateType: 'OMT',
        reduced: 0,
        reductionAmount: 0,
        registrationState: 'NY',
        sanitized: {
          issuingAgency: 'Department of Transportation (NYC DOT)',
          vehicleBodyType: undefined,
        },
        streetCode1: undefined,
        streetCode2: undefined,
        streetCode3: undefined,
        streetName: undefined,
        subDivision: undefined,
        summonsImage: {
          url: 'http://nycserv.nyc.gov/NYCServWeb/ShowImage?searchID=VGtSbk1FOVVUVFZQVkdjelRYYzlQUT09&locationName=_____________________',
          description: 'View Summons',
        },
        summonsNumber: '4849399873',
        toHoursInEffect: undefined,
        unregisteredVehicle: undefined,
        vehicleBodyType: undefined,
        vehicleColor: undefined,
        vehicleExpirationDate: undefined,
        vehicleMake: undefined,
        vehicleYear: undefined,
        violationCode: '36',
        violationCounty: 'Manhattan' as Borough,
        violationInFrontOfOrOpposite: undefined,
        violationLegalCode: undefined,
        violationLocation: undefined,
        violationPostCode: undefined,
        violationPrecinct: 0,
        violationTime: '07:55P',
      },
      {
        amountDue: undefined,
        dateFirstObserved: '0',
        daysParkingInEffect: undefined,
        feetFromCurb: '0',
        fineAmount: undefined,
        fined: undefined,
        formattedTime: '2023-07-02T19:55:00.000-04:00',
        formattedTimeEastern: '2023-07-02T19:55:00.000-04:00',
        formattedTimeUtc: '2023-07-02T23:55:00.000Z',
        fromDatabases: [
          {
            dataUpdatedAt: '2025-03-16T19:36:56.000Z',
            endpoint: 'https://data.cityofnewyork.us/resource/pvqr-7yc4.json',
            name: 'Parking Violations Issued - Fiscal Year 2024',
          },
        ],
        fromHoursInEffect: undefined,
        houseNumber: undefined,
        humanizedDescription:
          'School Zone Speed Camera Violation' as HumanizedDescription,
        interestAmount: undefined,
        intersectingStreet: 'S ST',
        issueDate: '2023-07-02T00:00:00.000',
        issuerCode: '0',
        issuerCommand: undefined,
        issuerPrecinct: 0,
        issuerSquad: undefined,
        issuingAgency: 'V',
        judgmentEntryDate: undefined,
        lawSection: '1180',
        location: 'Sb West St @ W Thames St',
        meterNumber: undefined,
        outstanding: undefined,
        paid: undefined,
        paymentAmount: undefined,
        penaltyAmount: undefined,
        plateId: '1E65H',
        plateType: 'OMT',
        reduced: undefined,
        reductionAmount: undefined,
        registrationState: 'NY',
        sanitized: {
          issuingAgency: 'Department of Transportation (NYC DOT)',
          vehicleBodyType: 'Taxi',
        },
        streetCode1: '0',
        streetCode2: '30640',
        streetCode3: '0',
        streetName: 'SB WEST ST @ W THAME',
        subDivision: 'B',
        summonsImage: undefined,
        summonsNumber: '4849399873',
        toHoursInEffect: undefined,
        unregisteredVehicle: undefined,
        vehicleBodyType: 'TAXI',
        vehicleColor: 'YW',
        vehicleExpirationDate: '0.00000000',
        vehicleMake: 'TOYOT',
        vehicleYear: '2016',
        violationCode: '36',
        violationCounty: 'Manhattan' as Borough,
        violationInFrontOfOrOpposite: undefined,
        violationLegalCode: 'T',
        violationLocation: undefined,
        violationPostCode: undefined,
        violationPrecinct: 0,
        violationTime: '0755P',
      },
    ]

    const expectedViolations = [
      {
        amountDue: 0,
        dateFirstObserved: '0',
        daysParkingInEffect: undefined,
        feetFromCurb: '0',
        fineAmount: 50,
        fined: 50,
        formattedTime: '2023-07-02T19:55:00.000-04:00',
        formattedTimeEastern: '2023-07-02T19:55:00.000-04:00',
        formattedTimeUtc: '2023-07-02T23:55:00.000Z',
        fromDatabases: [
          {
            dataUpdatedAt: '2025-03-16T19:36:56.000Z',
            endpoint: 'https://data.cityofnewyork.us/resource/pvqr-7yc4.json',
            name: 'Parking Violations Issued - Fiscal Year 2024',
          },
          {
            dataUpdatedAt: '2025-03-29T09:21:18.000Z',
            endpoint: 'https://data.cityofnewyork.us/resource/nc67-uf89.json',
            name: 'Open Parking and Camera Violations',
          },
        ],
        fromHoursInEffect: undefined,
        houseNumber: undefined,
        humanizedDescription:
          'School Zone Speed Camera Violation' as HumanizedDescription,
        interestAmount: 0,
        intersectingStreet: 'S ST',
        issueDate: '2023-07-02T00:00:00.000',
        issuerCode: '0',
        issuerCommand: undefined,
        issuerPrecinct: 0,
        issuerSquad: undefined,
        issuingAgency: 'V',
        judgmentEntryDate: undefined,
        lawSection: '1180',
        location: 'Sb West St @ W Thames St',
        meterNumber: undefined,
        outstanding: 0,
        paid: 50,
        paymentAmount: 50,
        penaltyAmount: 0,
        plateId: '1E65H',
        plateType: 'OMT',
        reduced: 0,
        reductionAmount: 0,
        registrationState: 'NY',
        sanitized: {
          issuingAgency: 'Department of Transportation (NYC DOT)',
          vehicleBodyType: 'Taxi',
        },
        streetCode1: '0',
        streetCode2: '30640',
        streetCode3: '0',
        streetName: 'SB WEST ST @ W THAME',
        subDivision: 'B',
        summonsImage: {
          url: 'http://nycserv.nyc.gov/NYCServWeb/ShowImage?searchID=VGtSbk1FOVVUVFZQVkdjelRYYzlQUT09&locationName=_____________________',
          description: 'View Summons',
        },
        summonsNumber: '4849399873',
        toHoursInEffect: undefined,
        unregisteredVehicle: undefined,
        vehicleBodyType: 'TAXI',
        vehicleColor: 'YW',
        vehicleExpirationDate: '0.00000000',
        vehicleMake: 'TOYOT',
        vehicleYear: '2016',
        violationCode: '36',
        violationCounty: 'Manhattan',
        violationInFrontOfOrOpposite: undefined,
        violationLegalCode: 'T',
        violationLocation: undefined,
        violationPostCode: undefined,
        violationPrecinct: 0,
        violationTime: '0755P',
      },
    ]

    const mergedViolations = mergeDuplicateViolations(violations)

    expect(mergedViolations).toEqual(expectedViolations)
    expect(mergedViolations.length).toBe(1)
  })

  it('should not merge violations with different summons numbers', async () => {
    const violations: Violation[] = [
      {
        amountDue: undefined,
        dateFirstObserved: '0',
        daysParkingInEffect: undefined,
        feetFromCurb: '0',
        fineAmount: undefined,
        fined: undefined,
        formattedTime: '2023-02-25T01:42:00.000-05:00',
        formattedTimeEastern: '2023-02-25T01:42:00.000-05:00',
        formattedTimeUtc: '2023-02-25T06:42:00.000Z',
        fromDatabases: [
          {
            dataUpdatedAt: '2023-11-14T17:54:58.000Z',
            endpoint: 'https://data.cityofnewyork.us/resource/869v-vr48.json',
            name: 'Parking Violations Issued - Fiscal Year 2023',
          },
        ],
        fromHoursInEffect: undefined,
        houseNumber: undefined,
        humanizedDescription:
          'School Zone Speed Camera Violation' as HumanizedDescription,
        interestAmount: undefined,
        intersectingStreet: 'N ST',
        issueDate: '2023-02-25T00:00:00.000',
        issuerCode: '0',
        issuerCommand: undefined,
        issuerPrecinct: 0,
        issuerSquad: undefined,
        issuingAgency: 'V',
        judgmentEntryDate: undefined,
        lawSection: '1180',
        location: 'Sb Adams St @ Johnson St',
        meterNumber: undefined,
        outstanding: undefined,
        paid: undefined,
        paymentAmount: undefined,
        penaltyAmount: undefined,
        plateId: '1E65H',
        plateType: 'OMT',
        reduced: undefined,
        reductionAmount: undefined,
        registrationState: 'NY',
        sanitized: {
          issuingAgency: 'Department of Transportation (NYC DOT)',
          vehicleBodyType: 'Taxi',
        },
        streetCode1: '0',
        streetCode2: '0',
        streetCode3: '0',
        streetName: 'SB ADAMS ST @ JOHNSO',
        subDivision: 'B',
        summonsImage: undefined,
        summonsNumber: '4829315751',
        toHoursInEffect: undefined,
        unregisteredVehicle: undefined,
        vehicleBodyType: 'TAXI',
        vehicleColor: 'YW',
        vehicleExpirationDate: '0',
        vehicleMake: 'TOYOT',
        vehicleYear: '2016',
        violationCode: '36',
        violationCounty: 'Brooklyn' as Borough,
        violationInFrontOfOrOpposite: undefined,
        violationLegalCode: 'T',
        violationLocation: undefined,
        violationPostCode: undefined,
        violationPrecinct: 0,
        violationTime: '0142A',
      },
      {
        amountDue: undefined,
        dateFirstObserved: '0',
        daysParkingInEffect: undefined,
        feetFromCurb: '0',
        fineAmount: undefined,
        fined: undefined,
        formattedTime: '2023-04-16T21:20:00.000-04:00',
        formattedTimeEastern: '2023-04-16T21:20:00.000-04:00',
        formattedTimeUtc: '2023-04-17T01:20:00.000Z',
        fromDatabases: [
          {
            dataUpdatedAt: '2023-11-14T17:54:58.000Z',
            endpoint: 'https://data.cityofnewyork.us/resource/869v-vr48.json',
            name: 'Parking Violations Issued - Fiscal Year 2023',
          },
        ],
        fromHoursInEffect: undefined,
        houseNumber: undefined,
        humanizedDescription:
          'School Zone Speed Camera Violation' as HumanizedDescription,
        interestAmount: undefined,
        intersectingStreet: '42ND ST',
        issueDate: '2023-04-16T00:00:00.000',
        issuerCode: '0',
        issuerCommand: undefined,
        issuerPrecinct: 0,
        issuerSquad: undefined,
        issuingAgency: 'V',
        judgmentEntryDate: undefined,
        lawSection: '1180',
        location: 'Wb Astoria Blvd N @ 42nd St',
        meterNumber: undefined,
        outstanding: undefined,
        paid: undefined,
        paymentAmount: undefined,
        penaltyAmount: undefined,
        plateId: '1E65H',
        plateType: 'OMT',
        reduced: undefined,
        reductionAmount: undefined,
        registrationState: 'NY',
        sanitized: {
          issuingAgency: 'Department of Transportation (NYC DOT)',
          vehicleBodyType: 'Taxi',
        },
        streetCode1: '0',
        streetCode2: '0',
        streetCode3: '0',
        streetName: 'WB ASTORIA BLVD N @',
        subDivision: 'B',
        summonsImage: undefined,
        summonsNumber: '4836347026',
        toHoursInEffect: undefined,
        unregisteredVehicle: undefined,
        vehicleBodyType: 'TAXI',
        vehicleColor: 'YW',
        vehicleExpirationDate: '0',
        vehicleMake: 'TOYOT',
        vehicleYear: '2016',
        violationCode: '36',
        violationCounty: 'Queens' as Borough,
        violationInFrontOfOrOpposite: undefined,
        violationLegalCode: 'T',
        violationLocation: undefined,
        violationPostCode: undefined,
        violationPrecinct: 0,
        violationTime: '0920P',
      },
    ]

    const mergedViolations = mergeDuplicateViolations(violations)

    expect(mergedViolations).toEqual(violations)
    expect(mergedViolations.length).toBe(2)
  })
})
