export enum IssuingAgency {
  AmtrakPolice = 'Amtrak PD',
  BoardOfEstimate = 'Board of Est.',
  Conrail = 'Conrail',
  FireDepartmentOfNewYork = 'FDNY',
  LongIslandRailRoad = 'LIRR',
  MetroNorthRailRoad = 'MNRR',
  NewYorkCityDepartmentOfCorrection = 'NYC DOC',
  NewYorkCityDepartmentOfHealthAndMentalHygiene = 'NYC DHMH',
  NewYorkCityDepartmentOfParksAndRecreation = 'NYC Parks',
  NewYorkCityDepartmentOfSanitation = 'DSNY',
  NewYorkCityDepartmentOfSmallBusinessServices = 'NYC SBS',
  NewYorkCityDepartmentOfTransportation = 'NYC DOT',
  NewYorkCityHealthAndHospitals = 'NYC Hospitals',
  NewYorkCityHousingAuthority = 'NYCHA',
  NewYorkCitySheriff = 'NYC Sheriff',
  NewYorkCityTaxiAndLimousineCommission = 'NYC TLC',
  NewYorkCityTransitAuthority = 'NYCHA',
  NewYorkPoliceDepartment = 'NYPD',
  NewYorkPoliceDepartmentTrafficEnforcement = 'NYPD Traffic',
  NewYorkStateCourts = 'NYS Courts',
  NewYorkStateOfficeOfMentalHealth = 'NYS OMH',
  NewYorkStateOfficeForPeopleWithDevelopmentalDisabilities = 'NYS OPWDD',
  NewYorkStateParks = 'NYS Parks',
  Other = 'other',
  PortAuthorityOfNewYorkAndNewJersey = 'PANYNJ',
  RooseveltIslandSecurity = 'RIOC PSD',
  SnugHarborCulturalCenterRangers = 'Snug Harbor Rangers',
  SeaGatePoliceDepartment = 'Seagate PD',
  StatenIslandRapidTransitPolice = 'SIRT PD',
  SunyMaritimeCollege = 'SUNY Maritime',
  TriboroughBridgeAndTunnelAuthority = 'TBTA',
  WaterfrontCommissionOfNewYorkHarbor = 'Waterfront Commission',
}

const issuingAgencies: Record<string, IssuingAgency> = {
  1: IssuingAgency.NewYorkStateOfficeOfMentalHealth,
  2: IssuingAgency.NewYorkStateOfficeForPeopleWithDevelopmentalDisabilities,
  3: IssuingAgency.RooseveltIslandSecurity,
  4: IssuingAgency.SeaGatePoliceDepartment,
  5: IssuingAgency.SnugHarborCulturalCenterRangers,
  6: IssuingAgency.WaterfrontCommissionOfNewYorkHarbor,
  7: IssuingAgency.SunyMaritimeCollege,
  9: IssuingAgency.NewYorkCitySheriff,
  A: IssuingAgency.PortAuthorityOfNewYorkAndNewJersey,
  B: IssuingAgency.TriboroughBridgeAndTunnelAuthority,
  C: IssuingAgency.Conrail,
  D: IssuingAgency.NewYorkCityDepartmentOfSmallBusinessServices,
  'DEPARTMENT OF BUSINESS SERVICES':
    IssuingAgency.NewYorkCityDepartmentOfSmallBusinessServices,
  'DEPARTMENT OF SANITATION': IssuingAgency.NewYorkCityDepartmentOfSanitation,
  'DEPARTMENT OF TRANSPORTATION':
    IssuingAgency.NewYorkCityDepartmentOfTransportation,
  E: IssuingAgency.BoardOfEstimate,
  F: IssuingAgency.FireDepartmentOfNewYork,
  'Fire Department': IssuingAgency.FireDepartmentOfNewYork,
  G: IssuingAgency.NewYorkCityTaxiAndLimousineCommission,
  H: IssuingAgency.NewYorkCityHousingAuthority,
  'HOUSING AUTHORITY': IssuingAgency.NewYorkCityHousingAuthority,
  I: IssuingAgency.StatenIslandRapidTransitPolice,
  J: IssuingAgency.AmtrakPolice,
  K: IssuingAgency.NewYorkCityDepartmentOfParksAndRecreation,
  L: IssuingAgency.LongIslandRailRoad,
  'LONG ISLAND RAILROAD': IssuingAgency.LongIslandRailRoad,
  M: IssuingAgency.NewYorkCityTransitAuthority,
  'METRO NORTH RAILROAD POLICE': IssuingAgency.MetroNorthRailRoad,
  N: IssuingAgency.NewYorkStateParks,
  'NYC OFFICE OF THE SHERIFF': IssuingAgency.NewYorkCitySheriff,
  'NYC TRANSIT AUTHORITY MANAGERS': IssuingAgency.NewYorkCityTransitAuthority,
  'NYS COURT OFFICERS': IssuingAgency.NewYorkStateCourts,
  'NYS PARKS POLICE': IssuingAgency.NewYorkStateParks,
  O: IssuingAgency.NewYorkStateCourts,
  'OTHER/UNKNOWN AGENCIES': IssuingAgency.Other,
  P: IssuingAgency.NewYorkPoliceDepartment,
  'PARKING CONTROL UNIT': IssuingAgency.NewYorkCityDepartmentOfTransportation,
  'PARKS DEPARTMENT': IssuingAgency.NewYorkCityDepartmentOfParksAndRecreation,
  'POLICE DEPARTMENT': IssuingAgency.NewYorkPoliceDepartment,
  'PORT AUTHORITY': IssuingAgency.PortAuthorityOfNewYorkAndNewJersey,
  Q: IssuingAgency.NewYorkCityDepartmentOfCorrection,
  R: IssuingAgency.NewYorkCityTransitAuthority,
  S: IssuingAgency.NewYorkCityDepartmentOfSanitation,
  T: IssuingAgency.NewYorkPoliceDepartmentTrafficEnforcement,
  'TAXI AND LIMOUSINE COMMISSION':
    IssuingAgency.NewYorkCityTaxiAndLimousineCommission,
  TRAFFIC: IssuingAgency.NewYorkPoliceDepartmentTrafficEnforcement,
  'TRANSIT AUTHORITY': IssuingAgency.NewYorkCityTransitAuthority,
  'TRIBOROUGH BRIDGE AND TUNNEL POLICE':
    IssuingAgency.TriboroughBridgeAndTunnelAuthority,
  U: IssuingAgency.NewYorkCityDepartmentOfTransportation,
  V: IssuingAgency.NewYorkCityDepartmentOfTransportation,
  W: IssuingAgency.NewYorkCityDepartmentOfHealthAndMentalHygiene,
  X: IssuingAgency.Other,
  Y: IssuingAgency.NewYorkCityHealthAndHospitals,
  Z: IssuingAgency.MetroNorthRailRoad,
}

export default issuingAgencies
