export enum Borough {
  Bronx = 'The Bronx',
  Brooklyn = 'Brooklyn',
  Manhattan = 'Manhattan',
  NoBoroughAvailable = 'No Borough Available',
  Queens = 'Queens',
  StatenIsland = 'Staten Island',
}

const boroughAbbreviations: Record<string, Borough> = {
  BRONX: Borough.Bronx,
  Bronx: Borough.Bronx,
  BROOK: Borough.Brooklyn,
  Brook: Borough.Brooklyn,
  BX: Borough.Bronx,
  Bx: Borough.Bronx,
  BK: Borough.Brooklyn,
  Bk: Borough.Brooklyn,
  K: Borough.Brooklyn,
  KINGS: Borough.Brooklyn,
  Kings: Borough.Brooklyn,
  MAH: Borough.Manhattan,
  MANHA: Borough.Manhattan,
  MN: Borough.Manhattan,
  NEUY: Borough.Manhattan,
  NY: Borough.Manhattan,
  PBX: Borough.Bronx,
  PK: Borough.Brooklyn,
  PNY: Borough.Manhattan,
  Q: Borough.Queens,
  QN: Borough.Queens,
  QNS: Borough.Queens,
  Qns: Borough.Queens,
  QUEEN: Borough.Queens,
  Queen: Borough.Queens,
  R: Borough.StatenIsland,
  RICH: Borough.StatenIsland,
  Rich: Borough.StatenIsland,
  ST: Borough.StatenIsland,
}

export const precinctsByBorough = {
  '1': Borough.Manhattan,
  '5': Borough.Manhattan,
  '6': Borough.Manhattan,
  '7': Borough.Manhattan,
  '9': Borough.Manhattan,
  '10': Borough.Manhattan,
  '13': Borough.Manhattan,
  '14': Borough.Manhattan,
  '17': Borough.Manhattan,
  '18': Borough.Manhattan,
  '19': Borough.Manhattan,
  '20': Borough.Manhattan,
  '22': Borough.Manhattan,
  '23': Borough.Manhattan,
  '24': Borough.Manhattan,
  '25': Borough.Manhattan,
  '26': Borough.Manhattan,
  '28': Borough.Manhattan,
  '30': Borough.Manhattan,
  '32': Borough.Manhattan,
  '33': Borough.Manhattan,
  '34': Borough.Manhattan,
  '40': Borough.Bronx,
  '41': Borough.Bronx,
  '42': Borough.Bronx,
  '43': Borough.Bronx,
  '44': Borough.Bronx,
  '45': Borough.Bronx,
  '46': Borough.Bronx,
  '47': Borough.Bronx,
  '48': Borough.Bronx,
  '49': Borough.Bronx,
  '50': Borough.Bronx,
  '52': Borough.Bronx,
  '60': Borough.Brooklyn,
  '61': Borough.Brooklyn,
  '62': Borough.Brooklyn,
  '63': Borough.Brooklyn,
  '66': Borough.Brooklyn,
  '67': Borough.Brooklyn,
  '68': Borough.Brooklyn,
  '69': Borough.Brooklyn,
  '70': Borough.Brooklyn,
  '71': Borough.Brooklyn,
  '72': Borough.Brooklyn,
  '73': Borough.Brooklyn,
  '75': Borough.Brooklyn,
  '76': Borough.Brooklyn,
  '77': Borough.Brooklyn,
  '78': Borough.Brooklyn,
  '79': Borough.Brooklyn,
  '81': Borough.Brooklyn,
  '83': Borough.Brooklyn,
  '84': Borough.Brooklyn,
  '88': Borough.Brooklyn,
  '90': Borough.Brooklyn,
  '94': Borough.Brooklyn,
  '100': Borough.Queens,
  '101': Borough.Queens,
  '102': Borough.Queens,
  '103': Borough.Queens,
  '104': Borough.Queens,
  '105': Borough.Queens,
  '106': Borough.Queens,
  '107': Borough.Queens,
  '108': Borough.Queens,
  '109': Borough.Queens,
  '110': Borough.Queens,
  '111': Borough.Queens,
  '112': Borough.Queens,
  '113': Borough.Queens,
  '114': Borough.Queens,
  '115': Borough.Queens,
  '120': Borough.StatenIsland,
  '121': Borough.StatenIsland,
  '122': Borough.StatenIsland,
  '123': Borough.StatenIsland,
  // [Borough.Bronx]: [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52],
  // [Borough.Brooklyn]: [
  //   60, 61, 62, 63, 66, 67, 68, 69, 70, 71, 72, 73, 75, 76, 77, 78, 79, 81, 83,
  //   84, 88, 90, 94,
  // ],
  // [Borough.Manhattan]: [
  //   1, 5, 6, 7, 9, 10, 13, 14, 17, 18, 19, 20, 22, 23, 24, 25, 26, 28, 30, 32,
  //   33, 34,
  // ],
  // [Borough.Queens]: [
  //   100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
  //   115,
  // ],
  // [Borough.StatenIsland]: [120, 121, 122, 123],
}

export default boroughAbbreviations
